export const queryKeys = {
  auth: {
    session: ['auth', 'session'] as const,
    sessions: ['auth', 'sessions'] as const,
  },
  patient: {
    profile: (mode: string) => ['patient', 'profile', mode] as const,
    dashboard: (mode: string) => ['patient', 'dashboard', mode] as const,
    appointments: (mode: string) => ['patient', 'appointments', mode] as const,
    transactions: (mode: string) => ['patient', 'transactions', mode] as const,
    notifications: (mode: string) => ['patient', 'notifications', mode] as const,
    invoices: (mode: string) => ['patient', 'invoices', mode] as const,
    invoice: (id: string) => ['patient', 'invoice', id] as const,
    invoiceAttachment: (id: string) => ['patient', 'invoice', id, 'attachment'] as const,
    providers: (country: string) => ['patient', 'providers', country] as const,
    providersByCategory: (category: string, country: string) =>
      ['patient', 'providers', category, country] as const,
    provider: (id: string | number) => ['patient', 'provider', id] as const,
    providerReviews: (id: string | number) => ['patient', 'provider', id, 'reviews'] as const,
    news: ['patient', 'news'] as const,
    credit: (mode: string) => ['patient', 'credit', mode] as const,
    prescriptionRequests: (mode: string) => ['patient', 'prescriptionRequests', mode] as const,
    ledgerStatus: ['patient', 'ledger', 'status'] as const,
    ledger: ['patient', 'ledger'] as const,
    ledgerAccess: ['patient', 'ledger', 'access'] as const,
  },
  sp: {
    dashboard: (mode: string) => ['sp', 'dashboard', mode] as const,
    profile: (mode: string) => ['sp', 'profile', mode] as const,
    appointments: (mode: string) => ['sp', 'appointments', mode] as const,
    patients: (mode: string) => ['sp', 'patients', mode] as const,
    payments: (mode: string) => ['sp', 'payments', mode] as const,
    invoices: (mode: string) => ['sp', 'invoices', mode] as const,
    notifications: (mode: string) => ['sp', 'notifications', mode] as const,
    settings: (mode: string) => ['sp', 'settings', mode] as const,
    sessions: (mode: string) => ['sp', 'sessions', mode] as const,
    payoutAccounts: (mode: string) => ['sp', 'payoutAccounts', mode] as const,
    appointment: (id: string) => ['sp', 'appointment', id] as const,
    patient: (id: string) => ['sp', 'patient', id] as const,
    invoice: (id: string) => ['sp', 'invoice', id] as const,
    invoiceAttachment: (id: string) => ['sp', 'invoice', id, 'attachment'] as const,
    prescriptionRequests: (mode: string) => ['sp', 'prescriptionRequests', mode] as const,
    prescriptionRequest: (id: string) => ['sp', 'prescriptionRequest', id] as const,
    visits: (mode: string) => ['sp', 'visits', mode] as const,
    ledger: (patientId: string) => ['sp', 'ledger', patientId] as const,
  },
  admin: {
    dashboard: ['admin', 'dashboard'] as const,
    news: ['admin', 'news'] as const,
    newsCategories: ['admin', 'news', 'categories'] as const,
    analytics: ['admin', 'analytics'] as const,
    applications: ['admin', 'applications'] as const,
    users: ['admin', 'users'] as const,
    user: (id: string) => ['admin', 'user', id] as const,
    providers: ['admin', 'providers'] as const,
    provider: (id: string) => ['admin', 'provider', id] as const,
    payments: (params: Record<string, unknown>) => ['admin', 'payments', params] as const,
    notifications: ['admin', 'notifications'] as const,
    activity: (country: string, limit = 10) => ['admin', 'activity', country, limit] as const,
    creditApplications: ['admin', 'credit-applications'] as const,
    ledgerAccess: (limit = 50) => ['admin', 'ledger-access', limit] as const,
  },
} as const
